version: '2.14'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: fin-track-api:1.0.0
    ports:
      - 8000:80
    depends_on:
      - db
    environment:
      PSQL_HOSTNAME: db
      PSQL_PORT: 5432
      PSQL_DBNAME: wallet
      PSQL_UNAME: postgres
      PSQL_PASS: fintrack2023
    restart: on-failure

  db:
    image: postgres:13.11
    ports:
      - 8432:5432
    environment:
      POSTGRES_DB: wallet
      POSTGRES_PASSWORD: fintrack2023
    volumes:
      - ./deploy/db_migrations.sql:/docker-entrypoint-initdb.d/db_migrations.sql
      - postgres-container:/var/lib/postgresql/data

volumes:
  postgres-container: